//THIS FILE IS ONLY FOR index.html 

import {github_username} from './constants.js'

const profile = {
    "login": "mihailv032",
    "id": 87564879,
    "node_id": "MDQ6VXNlcjg3NTY0ODc5",
    "avatar_url": "https://avatars.githubusercontent.com/u/87564879?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mihailv032",
    "html_url": "https://github.com/mihailv032",
    "followers_url": "https://api.github.com/users/mihailv032/followers",
    "following_url": "https://api.github.com/users/mihailv032/following{/other_user}",
    "gists_url": "https://api.github.com/users/mihailv032/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mihailv032/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mihailv032/subscriptions",
    "organizations_url": "https://api.github.com/users/mihailv032/orgs",
    "repos_url": "https://api.github.com/users/mihailv032/repos",
    "events_url": "https://api.github.com/users/mihailv032/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mihailv032/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Mihail",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 5,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2021-07-17T08:59:31Z",
    "updated_at": "2024-02-14T22:28:10Z"
}

main()
async function main(){
  try{
    createHeader();//generetes the github section header with the user profile
//    createBody() //gets and renders all the repos
  }catch(err){
    console.log(err)
  }
}


async function createHeader(data){
  try{
    //const accountReq = await fetch(`https://api.github.com/users/${github_username}`)
    //const data = await accountReq.json()
    console.log('here')
    const img = document.createElement("img");
    img.src = profile.avatar_url;
    img.style.width = "100px"
    document.getElementById("githubHead").append(img)

    const h6 = document.createElement("h2")
    h6.classList.add("my-3")
    h6.append(document.createTextNode(github_username))
    document.getElementById("githubHead").append(h6)

  }catch(err){
    console.log(err)
    return false;
  }
  
}

const repo = [
    {
        "id": 388245480,
        "node_id": "MDEwOlJlcG9zaXRvcnkzODgyNDU0ODA=",
        "name": "dotfiles",
        "full_name": "mihailv032/dotfiles",
        "private": false,
        "owner": {
            "login": "mihailv032",
            "id": 87564879,
            "node_id": "MDQ6VXNlcjg3NTY0ODc5",
            "avatar_url": "https://avatars.githubusercontent.com/u/87564879?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mihailv032",
            "html_url": "https://github.com/mihailv032",
            "followers_url": "https://api.github.com/users/mihailv032/followers",
            "following_url": "https://api.github.com/users/mihailv032/following{/other_user}",
            "gists_url": "https://api.github.com/users/mihailv032/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mihailv032/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mihailv032/subscriptions",
            "organizations_url": "https://api.github.com/users/mihailv032/orgs",
            "repos_url": "https://api.github.com/users/mihailv032/repos",
            "events_url": "https://api.github.com/users/mihailv032/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mihailv032/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/mihailv032/dotfiles",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/mihailv032/dotfiles",
        "forks_url": "https://api.github.com/repos/mihailv032/dotfiles/forks",
        "keys_url": "https://api.github.com/repos/mihailv032/dotfiles/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mihailv032/dotfiles/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mihailv032/dotfiles/teams",
        "hooks_url": "https://api.github.com/repos/mihailv032/dotfiles/hooks",
        "issue_events_url": "https://api.github.com/repos/mihailv032/dotfiles/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mihailv032/dotfiles/events",
        "assignees_url": "https://api.github.com/repos/mihailv032/dotfiles/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mihailv032/dotfiles/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mihailv032/dotfiles/tags",
        "blobs_url": "https://api.github.com/repos/mihailv032/dotfiles/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mihailv032/dotfiles/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mihailv032/dotfiles/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mihailv032/dotfiles/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mihailv032/dotfiles/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mihailv032/dotfiles/languages",
        "stargazers_url": "https://api.github.com/repos/mihailv032/dotfiles/stargazers",
        "contributors_url": "https://api.github.com/repos/mihailv032/dotfiles/contributors",
        "subscribers_url": "https://api.github.com/repos/mihailv032/dotfiles/subscribers",
        "subscription_url": "https://api.github.com/repos/mihailv032/dotfiles/subscription",
        "commits_url": "https://api.github.com/repos/mihailv032/dotfiles/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mihailv032/dotfiles/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mihailv032/dotfiles/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mihailv032/dotfiles/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mihailv032/dotfiles/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mihailv032/dotfiles/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mihailv032/dotfiles/merges",
        "archive_url": "https://api.github.com/repos/mihailv032/dotfiles/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mihailv032/dotfiles/downloads",
        "issues_url": "https://api.github.com/repos/mihailv032/dotfiles/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mihailv032/dotfiles/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mihailv032/dotfiles/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mihailv032/dotfiles/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mihailv032/dotfiles/labels{/name}",
        "releases_url": "https://api.github.com/repos/mihailv032/dotfiles/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mihailv032/dotfiles/deployments",
        "created_at": "2021-07-21T21:05:05Z",
        "updated_at": "2023-07-11T18:35:00Z",
        "pushed_at": "2024-02-06T18:38:29Z",
        "git_url": "git://github.com/mihailv032/dotfiles.git",
        "ssh_url": "git@github.com:mihailv032/dotfiles.git",
        "clone_url": "https://github.com/mihailv032/dotfiles.git",
        "svn_url": "https://github.com/mihailv032/dotfiles",
        "homepage": null,
        "size": 22108,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Shell",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 498674981,
        "node_id": "R_kgDOHbktJQ",
        "name": "jsplatformer",
        "full_name": "mihailv032/jsplatformer",
        "private": false,
        "owner": {
            "login": "mihailv032",
            "id": 87564879,
            "node_id": "MDQ6VXNlcjg3NTY0ODc5",
            "avatar_url": "https://avatars.githubusercontent.com/u/87564879?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mihailv032",
            "html_url": "https://github.com/mihailv032",
            "followers_url": "https://api.github.com/users/mihailv032/followers",
            "following_url": "https://api.github.com/users/mihailv032/following{/other_user}",
            "gists_url": "https://api.github.com/users/mihailv032/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mihailv032/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mihailv032/subscriptions",
            "organizations_url": "https://api.github.com/users/mihailv032/orgs",
            "repos_url": "https://api.github.com/users/mihailv032/repos",
            "events_url": "https://api.github.com/users/mihailv032/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mihailv032/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/mihailv032/jsplatformer",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/mihailv032/jsplatformer",
        "forks_url": "https://api.github.com/repos/mihailv032/jsplatformer/forks",
        "keys_url": "https://api.github.com/repos/mihailv032/jsplatformer/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mihailv032/jsplatformer/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mihailv032/jsplatformer/teams",
        "hooks_url": "https://api.github.com/repos/mihailv032/jsplatformer/hooks",
        "issue_events_url": "https://api.github.com/repos/mihailv032/jsplatformer/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mihailv032/jsplatformer/events",
        "assignees_url": "https://api.github.com/repos/mihailv032/jsplatformer/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mihailv032/jsplatformer/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mihailv032/jsplatformer/tags",
        "blobs_url": "https://api.github.com/repos/mihailv032/jsplatformer/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mihailv032/jsplatformer/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mihailv032/jsplatformer/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mihailv032/jsplatformer/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mihailv032/jsplatformer/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mihailv032/jsplatformer/languages",
        "stargazers_url": "https://api.github.com/repos/mihailv032/jsplatformer/stargazers",
        "contributors_url": "https://api.github.com/repos/mihailv032/jsplatformer/contributors",
        "subscribers_url": "https://api.github.com/repos/mihailv032/jsplatformer/subscribers",
        "subscription_url": "https://api.github.com/repos/mihailv032/jsplatformer/subscription",
        "commits_url": "https://api.github.com/repos/mihailv032/jsplatformer/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mihailv032/jsplatformer/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mihailv032/jsplatformer/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mihailv032/jsplatformer/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mihailv032/jsplatformer/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mihailv032/jsplatformer/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mihailv032/jsplatformer/merges",
        "archive_url": "https://api.github.com/repos/mihailv032/jsplatformer/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mihailv032/jsplatformer/downloads",
        "issues_url": "https://api.github.com/repos/mihailv032/jsplatformer/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mihailv032/jsplatformer/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mihailv032/jsplatformer/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mihailv032/jsplatformer/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mihailv032/jsplatformer/labels{/name}",
        "releases_url": "https://api.github.com/repos/mihailv032/jsplatformer/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mihailv032/jsplatformer/deployments",
        "created_at": "2022-06-01T09:38:23Z",
        "updated_at": "2022-06-05T21:23:50Z",
        "pushed_at": "2023-04-22T18:22:49Z",
        "git_url": "git://github.com/mihailv032/jsplatformer.git",
        "ssh_url": "git@github.com:mihailv032/jsplatformer.git",
        "clone_url": "https://github.com/mihailv032/jsplatformer.git",
        "svn_url": "https://github.com/mihailv032/jsplatformer",
        "homepage": null,
        "size": 419,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main"
    },
    {
        "id": 537397517,
        "node_id": "R_kgDOIAgJDQ",
        "name": "php",
        "full_name": "mihailv032/php",
        "private": false,
        "owner": {
            "login": "mihailv032",
            "id": 87564879,
            "node_id": "MDQ6VXNlcjg3NTY0ODc5",
            "avatar_url": "https://avatars.githubusercontent.com/u/87564879?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mihailv032",
            "html_url": "https://github.com/mihailv032",
            "followers_url": "https://api.github.com/users/mihailv032/followers",
            "following_url": "https://api.github.com/users/mihailv032/following{/other_user}",
            "gists_url": "https://api.github.com/users/mihailv032/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mihailv032/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mihailv032/subscriptions",
            "organizations_url": "https://api.github.com/users/mihailv032/orgs",
            "repos_url": "https://api.github.com/users/mihailv032/repos",
            "events_url": "https://api.github.com/users/mihailv032/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mihailv032/received_events",
            "type": "User", "site_admin": false
        },
        "html_url": "https://github.com/mihailv032/php",
        "description": "personal home page",
        "fork": false,
        "url": "https://api.github.com/repos/mihailv032/php",
        "forks_url": "https://api.github.com/repos/mihailv032/php/forks",
        "keys_url": "https://api.github.com/repos/mihailv032/php/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mihailv032/php/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mihailv032/php/teams",
        "hooks_url": "https://api.github.com/repos/mihailv032/php/hooks",
        "issue_events_url": "https://api.github.com/repos/mihailv032/php/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mihailv032/php/events",
        "assignees_url": "https://api.github.com/repos/mihailv032/php/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mihailv032/php/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mihailv032/php/tags",
        "blobs_url": "https://api.github.com/repos/mihailv032/php/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mihailv032/php/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mihailv032/php/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mihailv032/php/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mihailv032/php/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mihailv032/php/languages",
        "stargazers_url": "https://api.github.com/repos/mihailv032/php/stargazers",
        "contributors_url": "https://api.github.com/repos/mihailv032/php/contributors",
        "subscribers_url": "https://api.github.com/repos/mihailv032/php/subscribers",
        "subscription_url": "https://api.github.com/repos/mihailv032/php/subscription",
        "commits_url": "https://api.github.com/repos/mihailv032/php/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mihailv032/php/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mihailv032/php/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mihailv032/php/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mihailv032/php/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mihailv032/php/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mihailv032/php/merges",
        "archive_url": "https://api.github.com/repos/mihailv032/php/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mihailv032/php/downloads",
        "issues_url": "https://api.github.com/repos/mihailv032/php/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mihailv032/php/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mihailv032/php/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mihailv032/php/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mihailv032/php/labels{/name}",
        "releases_url": "https://api.github.com/repos/mihailv032/php/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mihailv032/php/deployments",
        "created_at": "2022-09-16T09:49:06Z",
        "updated_at": "2022-09-16T10:25:24Z",
        "pushed_at": "2023-10-14T11:00:45Z",
        "git_url": "git://github.com/mihailv032/php.git",
        "ssh_url": "git@github.com:mihailv032/php.git",
        "clone_url": "https://github.com/mihailv032/php.git",
        "svn_url": "https://github.com/mihailv032/php",
        "homepage": null,
        "size": 393803,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 704873217,
        "node_id": "R_kgDOKgODAQ",
        "name": "phpServer",
        "full_name": "mihailv032/phpServer",
        "private": false,
        "owner": {
            "login": "mihailv032",
            "id": 87564879,
            "node_id": "MDQ6VXNlcjg3NTY0ODc5",
            "avatar_url": "https://avatars.githubusercontent.com/u/87564879?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mihailv032",
            "html_url": "https://github.com/mihailv032",
            "followers_url": "https://api.github.com/users/mihailv032/followers",
            "following_url": "https://api.github.com/users/mihailv032/following{/other_user}",
            "gists_url": "https://api.github.com/users/mihailv032/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mihailv032/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mihailv032/subscriptions",
            "organizations_url": "https://api.github.com/users/mihailv032/orgs",
            "repos_url": "https://api.github.com/users/mihailv032/repos",
            "events_url": "https://api.github.com/users/mihailv032/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mihailv032/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/mihailv032/phpServer",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/mihailv032/phpServer",
        "forks_url": "https://api.github.com/repos/mihailv032/phpServer/forks",
        "keys_url": "https://api.github.com/repos/mihailv032/phpServer/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mihailv032/phpServer/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mihailv032/phpServer/teams",
        "hooks_url": "https://api.github.com/repos/mihailv032/phpServer/hooks",
        "issue_events_url": "https://api.github.com/repos/mihailv032/phpServer/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mihailv032/phpServer/events",
        "assignees_url": "https://api.github.com/repos/mihailv032/phpServer/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mihailv032/phpServer/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mihailv032/phpServer/tags",
        "blobs_url": "https://api.github.com/repos/mihailv032/phpServer/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mihailv032/phpServer/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mihailv032/phpServer/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mihailv032/phpServer/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mihailv032/phpServer/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mihailv032/phpServer/languages",
        "stargazers_url": "https://api.github.com/repos/mihailv032/phpServer/stargazers",
        "contributors_url": "https://api.github.com/repos/mihailv032/phpServer/contributors",
        "subscribers_url": "https://api.github.com/repos/mihailv032/phpServer/subscribers",
        "subscription_url": "https://api.github.com/repos/mihailv032/phpServer/subscription",
        "commits_url": "https://api.github.com/repos/mihailv032/phpServer/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mihailv032/phpServer/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mihailv032/phpServer/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mihailv032/phpServer/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mihailv032/phpServer/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mihailv032/phpServer/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mihailv032/phpServer/merges",
        "archive_url": "https://api.github.com/repos/mihailv032/phpServer/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mihailv032/phpServer/downloads",
        "issues_url": "https://api.github.com/repos/mihailv032/phpServer/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mihailv032/phpServer/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mihailv032/phpServer/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mihailv032/phpServer/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mihailv032/phpServer/labels{/name}",
        "releases_url": "https://api.github.com/repos/mihailv032/phpServer/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mihailv032/phpServer/deployments",
        "created_at": "2023-10-14T11:09:04Z",
        "updated_at": "2023-10-14T11:30:33Z",
        "pushed_at": "2024-02-14T20:21:09Z",
        "git_url": "git://github.com/mihailv032/phpServer.git",
        "ssh_url": "git@github.com:mihailv032/phpServer.git",
        "clone_url": "https://github.com/mihailv032/phpServer.git",
        "svn_url": "https://github.com/mihailv032/phpServer",
        "homepage": null,
        "size": 95,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
            "key": "gpl-2.0",
            "name": "GNU General Public License v2.0",
            "spdx_id": "GPL-2.0",
            "url": "https://api.github.com/licenses/gpl-2.0",
            "node_id": "MDc6TGljZW5zZTg="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 476858565,
        "node_id": "R_kgDOHGxIxQ",
        "name": "questionnaireApp",
        "full_name": "mihailv032/questionnaireApp",
        "private": false,
        "owner": {
            "login": "mihailv032",
            "id": 87564879,
            "node_id": "MDQ6VXNlcjg3NTY0ODc5",
            "avatar_url": "https://avatars.githubusercontent.com/u/87564879?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mihailv032",
            "html_url": "https://github.com/mihailv032",
            "followers_url": "https://api.github.com/users/mihailv032/followers",
            "following_url": "https://api.github.com/users/mihailv032/following{/other_user}",
            "gists_url": "https://api.github.com/users/mihailv032/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mihailv032/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mihailv032/subscriptions",
            "organizations_url": "https://api.github.com/users/mihailv032/orgs",
            "repos_url": "https://api.github.com/users/mihailv032/repos",
            "events_url": "https://api.github.com/users/mihailv032/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mihailv032/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/mihailv032/questionnaireApp",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/mihailv032/questionnaireApp",
        "forks_url": "https://api.github.com/repos/mihailv032/questionnaireApp/forks",
        "keys_url": "https://api.github.com/repos/mihailv032/questionnaireApp/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mihailv032/questionnaireApp/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mihailv032/questionnaireApp/teams",
        "hooks_url": "https://api.github.com/repos/mihailv032/questionnaireApp/hooks",
        "issue_events_url": "https://api.github.com/repos/mihailv032/questionnaireApp/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mihailv032/questionnaireApp/events",
        "assignees_url": "https://api.github.com/repos/mihailv032/questionnaireApp/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mihailv032/questionnaireApp/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mihailv032/questionnaireApp/tags",
        "blobs_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mihailv032/questionnaireApp/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mihailv032/questionnaireApp/languages",
        "stargazers_url": "https://api.github.com/repos/mihailv032/questionnaireApp/stargazers",
        "contributors_url": "https://api.github.com/repos/mihailv032/questionnaireApp/contributors",
        "subscribers_url": "https://api.github.com/repos/mihailv032/questionnaireApp/subscribers",
        "subscription_url": "https://api.github.com/repos/mihailv032/questionnaireApp/subscription",
        "commits_url": "https://api.github.com/repos/mihailv032/questionnaireApp/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mihailv032/questionnaireApp/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mihailv032/questionnaireApp/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mihailv032/questionnaireApp/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mihailv032/questionnaireApp/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mihailv032/questionnaireApp/merges",
        "archive_url": "https://api.github.com/repos/mihailv032/questionnaireApp/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mihailv032/questionnaireApp/downloads",
        "issues_url": "https://api.github.com/repos/mihailv032/questionnaireApp/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mihailv032/questionnaireApp/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mihailv032/questionnaireApp/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mihailv032/questionnaireApp/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mihailv032/questionnaireApp/labels{/name}",
        "releases_url": "https://api.github.com/repos/mihailv032/questionnaireApp/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mihailv032/questionnaireApp/deployments",
        "created_at": "2022-04-01T20:22:35Z",
        "updated_at": "2022-04-01T20:32:15Z",
        "pushed_at": "2022-05-24T22:56:41Z",
        "git_url": "git://github.com/mihailv032/questionnaireApp.git",
        "ssh_url": "git@github.com:mihailv032/questionnaireApp.git",
        "clone_url": "https://github.com/mihailv032/questionnaireApp.git",
        "svn_url": "https://github.com/mihailv032/questionnaireApp",
        "homepage": null,
        "size": 2330,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
      {
        "id": 476858565,
        "node_id": "R_kgDOHGxIxQ",
        "name": "questionnaireApp",
        "full_name": "mihailv032/questionnaireApp",
        "private": false,
        "owner": {
            "login": "mihailv032",
            "id": 87564879,
            "node_id": "MDQ6VXNlcjg3NTY0ODc5",
            "avatar_url": "https://avatars.githubusercontent.com/u/87564879?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mihailv032",
            "html_url": "https://github.com/mihailv032",
            "followers_url": "https://api.github.com/users/mihailv032/followers",
            "following_url": "https://api.github.com/users/mihailv032/following{/other_user}",
            "gists_url": "https://api.github.com/users/mihailv032/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mihailv032/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mihailv032/subscriptions",
            "organizations_url": "https://api.github.com/users/mihailv032/orgs",
            "repos_url": "https://api.github.com/users/mihailv032/repos",
            "events_url": "https://api.github.com/users/mihailv032/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mihailv032/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/mihailv032/questionnaireApp",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/mihailv032/questionnaireApp",
        "forks_url": "https://api.github.com/repos/mihailv032/questionnaireApp/forks",
        "keys_url": "https://api.github.com/repos/mihailv032/questionnaireApp/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mihailv032/questionnaireApp/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mihailv032/questionnaireApp/teams",
        "hooks_url": "https://api.github.com/repos/mihailv032/questionnaireApp/hooks",
        "issue_events_url": "https://api.github.com/repos/mihailv032/questionnaireApp/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mihailv032/questionnaireApp/events",
        "assignees_url": "https://api.github.com/repos/mihailv032/questionnaireApp/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mihailv032/questionnaireApp/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mihailv032/questionnaireApp/tags",
        "blobs_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mihailv032/questionnaireApp/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mihailv032/questionnaireApp/languages",
        "stargazers_url": "https://api.github.com/repos/mihailv032/questionnaireApp/stargazers",
        "contributors_url": "https://api.github.com/repos/mihailv032/questionnaireApp/contributors",
        "subscribers_url": "https://api.github.com/repos/mihailv032/questionnaireApp/subscribers",
        "subscription_url": "https://api.github.com/repos/mihailv032/questionnaireApp/subscription",
        "commits_url": "https://api.github.com/repos/mihailv032/questionnaireApp/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mihailv032/questionnaireApp/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mihailv032/questionnaireApp/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mihailv032/questionnaireApp/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mihailv032/questionnaireApp/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mihailv032/questionnaireApp/merges",
        "archive_url": "https://api.github.com/repos/mihailv032/questionnaireApp/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mihailv032/questionnaireApp/downloads",
        "issues_url": "https://api.github.com/repos/mihailv032/questionnaireApp/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mihailv032/questionnaireApp/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mihailv032/questionnaireApp/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mihailv032/questionnaireApp/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mihailv032/questionnaireApp/labels{/name}",
        "releases_url": "https://api.github.com/repos/mihailv032/questionnaireApp/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mihailv032/questionnaireApp/deployments",
        "created_at": "2022-04-01T20:22:35Z",
        "updated_at": "2022-04-01T20:32:15Z",
        "pushed_at": "2022-05-24T22:56:41Z",
        "git_url": "git://github.com/mihailv032/questionnaireApp.git",
        "ssh_url": "git@github.com:mihailv032/questionnaireApp.git",
        "clone_url": "https://github.com/mihailv032/questionnaireApp.git",
        "svn_url": "https://github.com/mihailv032/questionnaireApp",
        "homepage": null,
        "size": 2330,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 476858565,
        "node_id": "R_kgDOHGxIxQ",
        "name": "questionnaireApp",
        "full_name": "mihailv032/questionnaireApp",
        "private": false,
        "owner": {
            "login": "mihailv032",
            "id": 87564879,
            "node_id": "MDQ6VXNlcjg3NTY0ODc5",
            "avatar_url": "https://avatars.githubusercontent.com/u/87564879?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mihailv032",
            "html_url": "https://github.com/mihailv032",
            "followers_url": "https://api.github.com/users/mihailv032/followers",
            "following_url": "https://api.github.com/users/mihailv032/following{/other_user}",
            "gists_url": "https://api.github.com/users/mihailv032/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mihailv032/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mihailv032/subscriptions",
            "organizations_url": "https://api.github.com/users/mihailv032/orgs",
            "repos_url": "https://api.github.com/users/mihailv032/repos",
            "events_url": "https://api.github.com/users/mihailv032/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mihailv032/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/mihailv032/questionnaireApp",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/mihailv032/questionnaireApp",
        "forks_url": "https://api.github.com/repos/mihailv032/questionnaireApp/forks",
        "keys_url": "https://api.github.com/repos/mihailv032/questionnaireApp/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mihailv032/questionnaireApp/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mihailv032/questionnaireApp/teams",
        "hooks_url": "https://api.github.com/repos/mihailv032/questionnaireApp/hooks",
        "issue_events_url": "https://api.github.com/repos/mihailv032/questionnaireApp/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mihailv032/questionnaireApp/events",
        "assignees_url": "https://api.github.com/repos/mihailv032/questionnaireApp/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mihailv032/questionnaireApp/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mihailv032/questionnaireApp/tags",
        "blobs_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mihailv032/questionnaireApp/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mihailv032/questionnaireApp/languages",
        "stargazers_url": "https://api.github.com/repos/mihailv032/questionnaireApp/stargazers",
        "contributors_url": "https://api.github.com/repos/mihailv032/questionnaireApp/contributors",
        "subscribers_url": "https://api.github.com/repos/mihailv032/questionnaireApp/subscribers",
        "subscription_url": "https://api.github.com/repos/mihailv032/questionnaireApp/subscription",
        "commits_url": "https://api.github.com/repos/mihailv032/questionnaireApp/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mihailv032/questionnaireApp/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mihailv032/questionnaireApp/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mihailv032/questionnaireApp/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mihailv032/questionnaireApp/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mihailv032/questionnaireApp/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mihailv032/questionnaireApp/merges",
        "archive_url": "https://api.github.com/repos/mihailv032/questionnaireApp/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mihailv032/questionnaireApp/downloads",
        "issues_url": "https://api.github.com/repos/mihailv032/questionnaireApp/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mihailv032/questionnaireApp/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mihailv032/questionnaireApp/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mihailv032/questionnaireApp/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mihailv032/questionnaireApp/labels{/name}",
        "releases_url": "https://api.github.com/repos/mihailv032/questionnaireApp/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mihailv032/questionnaireApp/deployments",
        "created_at": "2022-04-01T20:22:35Z",
        "updated_at": "2022-04-01T20:32:15Z",
        "pushed_at": "2022-05-24T22:56:41Z",
        "git_url": "git://github.com/mihailv032/questionnaireApp.git",
        "ssh_url": "git@github.com:mihailv032/questionnaireApp.git",
        "clone_url": "https://github.com/mihailv032/questionnaireApp.git",
        "svn_url": "https://github.com/mihailv032/questionnaireApp",
        "homepage": null,
        "size": 2330,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    }

]
createBody()
async function createBody(){
  try{
//    const reposReq = await fetch(`https://api.github.com/users/${github_username}/repos`)
//    const repos = await reposReq.json()
//    console.log(repos)
    repo.forEach( repo => createGithubCard("githubCards",repo))

  }catch(err){
    console.log(err)
    return false;
  }
}

//this is the reason we have so many js frameworks
function createGithubCard(containerId,repoData){
  const container = document.getElementById(containerId)
  console.log(repoData)
  const div = document.createElement("div")
  const div2 = document.createElement("div")
  const h5 = document.createElement("h5")
  const h6 = document.createElement("h6")
  const p = document.createElement("p")
  const input = document.createElement("input")
  const btn = document.createElement("button")
  const btn2 = document.createElement("button")
  const titleAnchor = document.createElement("a")
  
  div.classList.add("card", "bg-secondary-subtle")
  div.style.width = "20rem"

  div2.classList.add("card-body")
  div.append(div2)

  h5.classList.add("card-title", "fw-bolder")
  console.log(repoData.name)
  titleAnchor.href = repoData.html_url
  titleAnchor.append(document.createTextNode(repoData.name))
  h5.append(titleAnchor)
  div2.append(h5)

  h6.classList.add("card-subtitle", "text-body-secondary")
  let created = new Date(repoData.created_at);
  created = created.getDate() + '/' + (created.getMonth() + 1) + '/' +  created.getFullYear();
  h6.append(document.createTextNode(`Created at: ${created}`))
  div2.append(h6)

  p.classList.add("card-text")
  p.append(document.createTextNode(repoData.description ? repoData.description : "no description added for this repo"))
  div2.append(p)

  input.value = repoData.ssh_url
  input.style.width = "100%"
  div2.append(input)

  btn.classList.add("btn", "btn-danger", "m-2")
  btn.append(document.createTextNode("copy"))

  //this is prob bad 4 optimization)))
  btn.addEventListener("click", e => { navigator.clipboard.writeText(input.value) })
  div2.append(btn)

  btn2.classList.add("btn", "btn-danger", "m-2")
  btn2.style.textAlign ="center"
  btn2.style.width = "80px"
  btn2.append(document.createTextNode("SSH"))

  btn2.addEventListener("click", e => {
    if(input.value === repoData.ssh_url){
      input.value = repoData.clone_url;
      btn2.textContent = "HTTPS"
    }else {
      input.value = repoData.ssh_url;
      btn2.textContent = "SSH"

    }
  })
  div2.append(btn2)


  container.append(div)
  

}

